# Configuration for Telco Customer Churn · MLOps
title: Telco Customer Churn · MLOps
author: Juan Camilo Mendoza Arango, Miguel Ángel Pérez Vargas y Paula Andrea Gómez Vargas

# 1. Configuración de Ejecución
execute:
  execute_notebooks: "off"

# 2. Extensiones de Markdown
parse:
  myst_enable_extensions:
    - colon_fence
    - amsmath
    - dollarmath
    - html_image

# 3. Configuración de HTML y Botones
html:
  use_issues_button: true
  use_repository_button: true
  use_download_button: true
  home_page_in_toc: true
  extra_navbar: "Universidad del Norte · Ingeniería de Sistemas"

# 4. Enlace al repositorio
repository:
  url: https://github.com/apaulag24/telco-churn-mlops
  branch: main
execute:
  execute_notebooks: "off"  # Esto evita que el servidor intente correr el código