name: deploy-book

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install jupyter-book myst-nb pandas numpy matplotlib seaborn scikit-learn xgboost catboost lightgbm pyarrow fastparquet

      - name: Build the book
        # Paso clave: Entramos a la carpeta interna antes de construir
        run: |
          cd telco-churn-mlops
          jupyter-book build .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Buscamos el resultado justo donde se creó
          path: "telco-churn-mlops/_build/html"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
