name: deploy-book

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install jupyter-book myst-nb pandas numpy matplotlib seaborn scikit-learn xgboost catboost lightgbm pyarrow fastparquet

      - name: Build the book
        run: |
          # 1. Creamos una carpeta totalmente nueva y vacía
          mkdir proyecto_limpio
          
          # 2. Copiamos SOLO lo necesario a esa carpeta (evitando carpetas repetidas)
          cp _config.yml _toc.yml intro.md requirements.txt proyecto_limpio/
          cp -r notebooks/ proyecto_limpio/
          cp -r data/ proyecto_limpio/
          
          # 3. Entramos y construimos desde ahí
          cd proyecto_limpio
          jupyter-book build . --all
          
          # 4. Movemos el resultado afuera para que sea fácil de encontrar
          cd ..
          mkdir -p output
          cp -r proyecto_limpio/_build/html/* output/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Apuntamos a la carpeta limpia que creamos al final
          path: "output"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
